/**
 * Country metadata for bulk generation.
 * Excludes countries that already have handcrafted pages.
 */

export interface CountryMeta {
  slug: string;
  name: string;
  demonym: string;
  region: 'europe' | 'asia' | 'americas' | 'middle-east' | 'africa' | 'oceania';
  subregion?: string;
  insuranceRequired: boolean;
  publicSystemName: string;
  currency: string;
  /** Approximate monthly cost for international insurance */
  insuranceCostRange: string;
  /** Approximate monthly cost for local/public healthcare */
  publicCostRange: string;
  /** Key visa types for expats */
  visaTypes: string[];
  /** Special notes about this country */
  notes?: string;
}

// Countries that already have handcrafted pages - SKIP THESE
export const existingSlugs = new Set([
  'spain', 'portugal', 'mexico', 'thailand', 'costa-rica', 'france',
  'italy', 'germany', 'uk', 'uae', 'singapore', 'indonesia', 'vietnam',
  'australia', 'canada', 'netherlands', 'panama', 'colombia', 'argentina',
  'japan', 'ecuador'
]);

export const countryMetadata: CountryMeta[] = [
  // =====================
  // EUROPE
  // =====================
  { slug: 'greece', name: 'Greece', demonym: 'Greek', region: 'europe', insuranceRequired: true, publicSystemName: 'EOPYY', currency: 'EUR', insuranceCostRange: '€100-250/month', publicCostRange: '€50-100/month', visaTypes: ['Digital Nomad Visa', 'Retirement Visa', 'Work Permit'] },
  { slug: 'croatia', name: 'Croatia', demonym: 'Croatian', region: 'europe', insuranceRequired: true, publicSystemName: 'HZZO', currency: 'EUR', insuranceCostRange: '€80-200/month', publicCostRange: '€40-80/month', visaTypes: ['Digital Nomad Visa', 'Temporary Stay Permit'] },
  { slug: 'ireland', name: 'Ireland', demonym: 'Irish', region: 'europe', insuranceRequired: false, publicSystemName: 'HSE', currency: 'EUR', insuranceCostRange: '€150-350/month', publicCostRange: '€50-100/month', visaTypes: ['Stamp 4', 'Critical Skills Permit', 'Stamp 0'] },
  { slug: 'poland', name: 'Poland', demonym: 'Polish', region: 'europe', insuranceRequired: true, publicSystemName: 'NFZ', currency: 'PLN', insuranceCostRange: '€80-180/month', publicCostRange: '€30-60/month', visaTypes: ['Temporary Residence Permit', 'EU Blue Card'] },
  { slug: 'czech-republic', name: 'Czech Republic', demonym: 'Czech', region: 'europe', insuranceRequired: true, publicSystemName: 'VZP', currency: 'CZK', insuranceCostRange: '€100-220/month', publicCostRange: '€40-80/month', visaTypes: ['Long-term Visa', 'Employee Card', 'Zivno Visa'] },
  { slug: 'hungary', name: 'Hungary', demonym: 'Hungarian', region: 'europe', insuranceRequired: true, publicSystemName: 'NEAK', currency: 'HUF', insuranceCostRange: '€70-160/month', publicCostRange: '€30-60/month', visaTypes: ['Residence Permit', 'White Card'] },
  { slug: 'austria', name: 'Austria', demonym: 'Austrian', region: 'europe', insuranceRequired: true, publicSystemName: 'ÖGK', currency: 'EUR', insuranceCostRange: '€150-350/month', publicCostRange: '€80-150/month', visaTypes: ['Red-White-Red Card', 'Settlement Permit'] },
  { slug: 'switzerland', name: 'Switzerland', demonym: 'Swiss', region: 'europe', insuranceRequired: true, publicSystemName: 'LAMal', currency: 'CHF', insuranceCostRange: 'CHF 300-600/month', publicCostRange: 'CHF 300-500/month', visaTypes: ['B Permit', 'C Permit', 'L Permit'] },
  { slug: 'belgium', name: 'Belgium', demonym: 'Belgian', region: 'europe', insuranceRequired: true, publicSystemName: 'INAMI/RIZIV', currency: 'EUR', insuranceCostRange: '€120-280/month', publicCostRange: '€100-150/month', visaTypes: ['D Visa', 'Professional Card'] },
  { slug: 'sweden', name: 'Sweden', demonym: 'Swedish', region: 'europe', insuranceRequired: false, publicSystemName: 'Försäkringskassan', currency: 'SEK', insuranceCostRange: '€150-350/month', publicCostRange: 'Included in taxes', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'norway', name: 'Norway', demonym: 'Norwegian', region: 'europe', insuranceRequired: false, publicSystemName: 'Helfo', currency: 'NOK', insuranceCostRange: '€180-400/month', publicCostRange: 'Included in taxes', visaTypes: ['Residence Permit', 'Skilled Worker Visa'] },
  { slug: 'denmark', name: 'Denmark', demonym: 'Danish', region: 'europe', insuranceRequired: false, publicSystemName: 'Sundhedsstyrelsen', currency: 'DKK', insuranceCostRange: '€150-350/month', publicCostRange: 'Included in taxes', visaTypes: ['Residence Permit', 'Green Card'] },
  { slug: 'finland', name: 'Finland', demonym: 'Finnish', region: 'europe', insuranceRequired: false, publicSystemName: 'Kela', currency: 'EUR', insuranceCostRange: '€150-320/month', publicCostRange: 'Included in taxes', visaTypes: ['Residence Permit', 'Startup Permit'] },
  { slug: 'romania', name: 'Romania', demonym: 'Romanian', region: 'europe', insuranceRequired: true, publicSystemName: 'CNAS', currency: 'RON', insuranceCostRange: '€60-140/month', publicCostRange: '€20-50/month', visaTypes: ['Long-stay Visa', 'Residence Permit'] },
  { slug: 'bulgaria', name: 'Bulgaria', demonym: 'Bulgarian', region: 'europe', insuranceRequired: true, publicSystemName: 'NHIF', currency: 'BGN', insuranceCostRange: '€50-120/month', publicCostRange: '€15-40/month', visaTypes: ['Type D Visa', 'Residence Permit'] },
  { slug: 'serbia', name: 'Serbia', demonym: 'Serbian', region: 'europe', insuranceRequired: true, publicSystemName: 'RFZO', currency: 'RSD', insuranceCostRange: '€50-120/month', publicCostRange: '€20-40/month', visaTypes: ['Temporary Residence', 'Digital Nomad Program'] },
  { slug: 'montenegro', name: 'Montenegro', demonym: 'Montenegrin', region: 'europe', insuranceRequired: true, publicSystemName: 'FZOM', currency: 'EUR', insuranceCostRange: '€60-140/month', publicCostRange: '€25-50/month', visaTypes: ['Temporary Residence', 'Digital Nomad Visa'] },
  { slug: 'albania', name: 'Albania', demonym: 'Albanian', region: 'europe', insuranceRequired: false, publicSystemName: 'FSDKSH', currency: 'ALL', insuranceCostRange: '€50-120/month', publicCostRange: '€15-35/month', visaTypes: ['Residence Permit', '1-Year Visa-Free'] },
  { slug: 'north-macedonia', name: 'North Macedonia', demonym: 'Macedonian', region: 'europe', insuranceRequired: true, publicSystemName: 'FZOM', currency: 'MKD', insuranceCostRange: '€40-100/month', publicCostRange: '€15-30/month', visaTypes: ['Temporary Residence Permit'] },
  { slug: 'slovenia', name: 'Slovenia', demonym: 'Slovenian', region: 'europe', insuranceRequired: true, publicSystemName: 'ZZZS', currency: 'EUR', insuranceCostRange: '€100-220/month', publicCostRange: '€50-100/month', visaTypes: ['Temporary Residence Permit', 'Single Permit'] },
  { slug: 'slovakia', name: 'Slovakia', demonym: 'Slovak', region: 'europe', insuranceRequired: true, publicSystemName: 'VšZP', currency: 'EUR', insuranceCostRange: '€80-180/month', publicCostRange: '€30-60/month', visaTypes: ['Temporary Residence', 'National Visa'] },
  { slug: 'lithuania', name: 'Lithuania', demonym: 'Lithuanian', region: 'europe', insuranceRequired: true, publicSystemName: 'TLK', currency: 'EUR', insuranceCostRange: '€70-160/month', publicCostRange: '€25-50/month', visaTypes: ['Temporary Residence Permit', 'EU Blue Card'] },
  { slug: 'latvia', name: 'Latvia', demonym: 'Latvian', region: 'europe', insuranceRequired: true, publicSystemName: 'NHS', currency: 'EUR', insuranceCostRange: '€70-160/month', publicCostRange: '€25-50/month', visaTypes: ['Temporary Residence Permit', 'Digital Nomad Visa'] },
  { slug: 'estonia', name: 'Estonia', demonym: 'Estonian', region: 'europe', insuranceRequired: true, publicSystemName: 'Haigekassa', currency: 'EUR', insuranceCostRange: '€80-180/month', publicCostRange: '€30-60/month', visaTypes: ['Digital Nomad Visa', 'Temporary Residence Permit'] },
  { slug: 'cyprus', name: 'Cyprus', demonym: 'Cypriot', region: 'europe', insuranceRequired: true, publicSystemName: 'GHS/GESY', currency: 'EUR', insuranceCostRange: '€100-220/month', publicCostRange: '€40-80/month', visaTypes: ['Pink Slip', 'Permanent Residence'] },
  { slug: 'malta', name: 'Malta', demonym: 'Maltese', region: 'europe', insuranceRequired: true, publicSystemName: 'NHS Malta', currency: 'EUR', insuranceCostRange: '€100-240/month', publicCostRange: '€40-80/month', visaTypes: ['Nomad Residence Permit', 'Global Residence Programme'] },
  { slug: 'luxembourg', name: 'Luxembourg', demonym: 'Luxembourgish', region: 'europe', insuranceRequired: true, publicSystemName: 'CNS', currency: 'EUR', insuranceCostRange: '€180-400/month', publicCostRange: '€100-180/month', visaTypes: ['Residence Permit', 'EU Blue Card'] },
  { slug: 'iceland', name: 'Iceland', demonym: 'Icelandic', region: 'europe', insuranceRequired: false, publicSystemName: 'Sjúkratryggingar Íslands', currency: 'ISK', insuranceCostRange: '€200-450/month', publicCostRange: 'Included in taxes', visaTypes: ['Residence Permit', 'Work Permit'] },
  { slug: 'andorra', name: 'Andorra', demonym: 'Andorran', region: 'europe', insuranceRequired: true, publicSystemName: 'CASS', currency: 'EUR', insuranceCostRange: '€150-350/month', publicCostRange: '€80-150/month', visaTypes: ['Passive Residence', 'Active Residence'] },
  { slug: 'monaco', name: 'Monaco', demonym: 'Monégasque', region: 'europe', insuranceRequired: true, publicSystemName: 'CCSS', currency: 'EUR', insuranceCostRange: '€300-600/month', publicCostRange: '€150-300/month', visaTypes: ['Residence Card'] },
  { slug: 'liechtenstein', name: 'Liechtenstein', demonym: 'Liechtensteiner', region: 'europe', insuranceRequired: true, publicSystemName: 'OKP', currency: 'CHF', insuranceCostRange: 'CHF 350-700/month', publicCostRange: 'CHF 300-500/month', visaTypes: ['Residence Permit'] },
  { slug: 'san-marino', name: 'San Marino', demonym: 'Sammarinese', region: 'europe', insuranceRequired: true, publicSystemName: 'ISS', currency: 'EUR', insuranceCostRange: '€120-280/month', publicCostRange: '€60-120/month', visaTypes: ['Residence Permit'] },
  { slug: 'bosnia-herzegovina', name: 'Bosnia and Herzegovina', demonym: 'Bosnian', region: 'europe', insuranceRequired: true, publicSystemName: 'FZO', currency: 'BAM', insuranceCostRange: '€40-100/month', publicCostRange: '€15-35/month', visaTypes: ['Temporary Residence Permit'] },
  { slug: 'kosovo', name: 'Kosovo', demonym: 'Kosovar', region: 'europe', insuranceRequired: true, publicSystemName: 'KFSHI', currency: 'EUR', insuranceCostRange: '€40-100/month', publicCostRange: '€10-25/month', visaTypes: ['Residence Permit'] },
  { slug: 'moldova', name: 'Moldova', demonym: 'Moldovan', region: 'europe', insuranceRequired: true, publicSystemName: 'CNAM', currency: 'MDL', insuranceCostRange: '€40-100/month', publicCostRange: '€10-25/month', visaTypes: ['Temporary Residence Permit'] },
  { slug: 'ukraine', name: 'Ukraine', demonym: 'Ukrainian', region: 'europe', insuranceRequired: true, publicSystemName: 'NHSU', currency: 'UAH', insuranceCostRange: '€40-100/month', publicCostRange: '€10-25/month', visaTypes: ['Type D Visa', 'Temporary Residence Permit'], notes: 'Check current situation due to ongoing conflict' },
  { slug: 'belarus', name: 'Belarus', demonym: 'Belarusian', region: 'europe', insuranceRequired: true, publicSystemName: 'State Healthcare', currency: 'BYN', insuranceCostRange: '€40-100/month', publicCostRange: '€15-30/month', visaTypes: ['Temporary Residence Permit'], notes: 'Limited expat infrastructure' },
  { slug: 'georgia', name: 'Georgia', demonym: 'Georgian', region: 'europe', insuranceRequired: false, publicSystemName: 'UHC', currency: 'GEL', insuranceCostRange: '€50-120/month', publicCostRange: '€20-40/month', visaTypes: ['1-Year Visa-Free', 'Residence Permit', 'Remotely from Georgia Program'] },
  { slug: 'armenia', name: 'Armenia', demonym: 'Armenian', region: 'europe', insuranceRequired: false, publicSystemName: 'State Healthcare', currency: 'AMD', insuranceCostRange: '€40-100/month', publicCostRange: '€15-30/month', visaTypes: ['Residence Permit', '180-Day Visa-Free'] },
  { slug: 'azerbaijan', name: 'Azerbaijan', demonym: 'Azerbaijani', region: 'europe', insuranceRequired: true, publicSystemName: 'DSMF', currency: 'AZN', insuranceCostRange: '€50-120/month', publicCostRange: '€20-40/month', visaTypes: ['Temporary Residence Permit'] },
  { slug: 'turkey', name: 'Turkey', demonym: 'Turkish', region: 'europe', insuranceRequired: true, publicSystemName: 'SGK', currency: 'TRY', insuranceCostRange: '$80-180/month', publicCostRange: '$30-60/month', visaTypes: ['Tourist Residence Permit', 'Work Permit', 'Family Residence Permit'] },

  // =====================
  // ASIA
  // =====================
  { slug: 'south-korea', name: 'South Korea', demonym: 'Korean', region: 'asia', insuranceRequired: true, publicSystemName: 'NHIS', currency: 'KRW', insuranceCostRange: '$150-350/month', publicCostRange: '$80-150/month', visaTypes: ['D-10 Job Seeker', 'E-7 Skilled Worker', 'F-2 Residence'] },
  { slug: 'taiwan', name: 'Taiwan', demonym: 'Taiwanese', region: 'asia', insuranceRequired: true, publicSystemName: 'NHI', currency: 'TWD', insuranceCostRange: '$100-250/month', publicCostRange: '$20-40/month', visaTypes: ['Gold Card', 'Resident Visa', 'Employment Gold Card'] },
  { slug: 'hong-kong', name: 'Hong Kong', demonym: 'Hong Konger', region: 'asia', insuranceRequired: false, publicSystemName: 'HA', currency: 'HKD', insuranceCostRange: '$200-450/month', publicCostRange: '$15-30/visit', visaTypes: ['Employment Visa', 'Investment Visa', 'Quality Migrant'] },
  { slug: 'philippines', name: 'Philippines', demonym: 'Filipino', region: 'asia', insuranceRequired: false, publicSystemName: 'PhilHealth', currency: 'PHP', insuranceCostRange: '$80-200/month', publicCostRange: '$10-25/month', visaTypes: ['SRRV', '13(a) Marriage Visa', 'SIRV'] },
  { slug: 'malaysia', name: 'Malaysia', demonym: 'Malaysian', region: 'asia', insuranceRequired: false, publicSystemName: 'MOH', currency: 'MYR', insuranceCostRange: '$100-250/month', publicCostRange: '$20-50/month', visaTypes: ['MM2H', 'DE Rantau', 'Employment Pass'] },
  { slug: 'cambodia', name: 'Cambodia', demonym: 'Cambodian', region: 'asia', insuranceRequired: false, publicSystemName: 'NSSF', currency: 'USD', insuranceCostRange: '$80-180/month', publicCostRange: '$10-30/month', visaTypes: ['EB Visa', 'Retirement Visa'] },
  { slug: 'laos', name: 'Laos', demonym: 'Laotian', region: 'asia', insuranceRequired: false, publicSystemName: 'State Healthcare', currency: 'LAK', insuranceCostRange: '$60-150/month', publicCostRange: '$10-25/month', visaTypes: ['Business Visa', 'Retirement Visa'] },
  { slug: 'myanmar', name: 'Myanmar', demonym: 'Burmese', region: 'asia', insuranceRequired: false, publicSystemName: 'MOH', currency: 'MMK', insuranceCostRange: '$60-150/month', publicCostRange: '$5-15/month', visaTypes: ['Business Visa', 'Social Visa'], notes: 'Check current situation' },
  { slug: 'nepal', name: 'Nepal', demonym: 'Nepalese', region: 'asia', insuranceRequired: false, publicSystemName: 'State Healthcare', currency: 'NPR', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Tourist Visa', 'Non-Tourist Visa'] },
  { slug: 'sri-lanka', name: 'Sri Lanka', demonym: 'Sri Lankan', region: 'asia', insuranceRequired: false, publicSystemName: 'State Healthcare', currency: 'LKR', insuranceCostRange: '$60-150/month', publicCostRange: '$10-25/month', visaTypes: ['ETA', 'Residence Visa', 'Digital Nomad Visa'] },
  { slug: 'bangladesh', name: 'Bangladesh', demonym: 'Bangladeshi', region: 'asia', insuranceRequired: false, publicSystemName: 'DGHS', currency: 'BDT', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit', 'Business Visa'] },
  { slug: 'pakistan', name: 'Pakistan', demonym: 'Pakistani', region: 'asia', insuranceRequired: false, publicSystemName: 'State Healthcare', currency: 'PKR', insuranceCostRange: '$50-120/month', publicCostRange: '$10-20/month', visaTypes: ['Work Visa', 'Business Visa'] },
  { slug: 'india', name: 'India', demonym: 'Indian', region: 'asia', insuranceRequired: false, publicSystemName: 'Ayushman Bharat', currency: 'INR', insuranceCostRange: '$60-150/month', publicCostRange: '$10-30/month', visaTypes: ['Employment Visa', 'Business Visa', 'Entry Visa'] },
  { slug: 'maldives', name: 'Maldives', demonym: 'Maldivian', region: 'asia', insuranceRequired: false, publicSystemName: 'Aasandha', currency: 'MVR', insuranceCostRange: '$100-250/month', publicCostRange: 'N/A for expats', visaTypes: ['Work Permit', 'Business Visa'] },
  { slug: 'brunei', name: 'Brunei', demonym: 'Bruneian', region: 'asia', insuranceRequired: false, publicSystemName: 'MOH', currency: 'BND', insuranceCostRange: '$100-250/month', publicCostRange: '$1-5/visit', visaTypes: ['Employment Pass', 'Dependent Pass'] },
  { slug: 'mongolia', name: 'Mongolia', demonym: 'Mongolian', region: 'asia', insuranceRequired: true, publicSystemName: 'State Healthcare', currency: 'MNT', insuranceCostRange: '$50-120/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'kazakhstan', name: 'Kazakhstan', demonym: 'Kazakh', region: 'asia', insuranceRequired: true, publicSystemName: 'FSHI', currency: 'KZT', insuranceCostRange: '$60-150/month', publicCostRange: '$15-35/month', visaTypes: ['Work Permit', 'Business Visa'] },
  { slug: 'uzbekistan', name: 'Uzbekistan', demonym: 'Uzbek', region: 'asia', insuranceRequired: true, publicSystemName: 'State Healthcare', currency: 'UZS', insuranceCostRange: '$40-100/month', publicCostRange: '$10-20/month', visaTypes: ['Work Permit', 'E-Visa'] },
  { slug: 'kyrgyzstan', name: 'Kyrgyzstan', demonym: 'Kyrgyz', region: 'asia', insuranceRequired: false, publicSystemName: 'MHIF', currency: 'KGS', insuranceCostRange: '$40-100/month', publicCostRange: '$5-15/month', visaTypes: ['Visa-Free 60 days', 'Residence Permit'] },
  { slug: 'tajikistan', name: 'Tajikistan', demonym: 'Tajik', region: 'asia', insuranceRequired: true, publicSystemName: 'State Healthcare', currency: 'TJS', insuranceCostRange: '$40-100/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit', 'E-Visa'] },
  { slug: 'turkmenistan', name: 'Turkmenistan', demonym: 'Turkmen', region: 'asia', insuranceRequired: true, publicSystemName: 'State Healthcare', currency: 'TMT', insuranceCostRange: '$50-120/month', publicCostRange: '$10-20/month', visaTypes: ['Work Visa', 'Transit Visa'], notes: 'Very restricted access' },
  { slug: 'china', name: 'China', demonym: 'Chinese', region: 'asia', insuranceRequired: false, publicSystemName: 'Urban Employee BMI', currency: 'CNY', insuranceCostRange: '$150-350/month', publicCostRange: '$30-80/month', visaTypes: ['Z Visa', 'R Visa', 'M Visa'] },
  { slug: 'macau', name: 'Macau', demonym: 'Macanese', region: 'asia', insuranceRequired: false, publicSystemName: 'SSM', currency: 'MOP', insuranceCostRange: '$150-350/month', publicCostRange: '$10-25/visit', visaTypes: ['Blue Card', 'Work Permit'] },

  // =====================
  // AMERICAS
  // =====================
  { slug: 'brazil', name: 'Brazil', demonym: 'Brazilian', region: 'americas', insuranceRequired: false, publicSystemName: 'SUS', currency: 'BRL', insuranceCostRange: '$100-250/month', publicCostRange: 'Free (SUS)', visaTypes: ['VITEM V', 'Digital Nomad Visa', 'Retirement Visa'] },
  { slug: 'chile', name: 'Chile', demonym: 'Chilean', region: 'americas', insuranceRequired: false, publicSystemName: 'FONASA', currency: 'CLP', insuranceCostRange: '$100-250/month', publicCostRange: '$30-70/month', visaTypes: ['Temporary Residence', 'Subject to Contract'] },
  { slug: 'peru', name: 'Peru', demonym: 'Peruvian', region: 'americas', insuranceRequired: false, publicSystemName: 'SIS/EsSalud', currency: 'PEN', insuranceCostRange: '$80-180/month', publicCostRange: '$20-40/month', visaTypes: ['Work Visa', 'Investor Visa', 'Rentista Visa'] },
  { slug: 'uruguay', name: 'Uruguay', demonym: 'Uruguayan', region: 'americas', insuranceRequired: false, publicSystemName: 'ASSE/Mutualistas', currency: 'UYU', insuranceCostRange: '$100-220/month', publicCostRange: '$40-80/month', visaTypes: ['Temporary Residence', 'Rentista Visa'] },
  { slug: 'paraguay', name: 'Paraguay', demonym: 'Paraguayan', region: 'americas', insuranceRequired: false, publicSystemName: 'IPS', currency: 'PYG', insuranceCostRange: '$60-140/month', publicCostRange: '$15-35/month', visaTypes: ['Temporary Residence', 'Permanent Residence'] },
  { slug: 'bolivia', name: 'Bolivia', demonym: 'Bolivian', region: 'americas', insuranceRequired: false, publicSystemName: 'SUS', currency: 'BOB', insuranceCostRange: '$50-120/month', publicCostRange: '$10-25/month', visaTypes: ['Specific Purpose Visa', 'Residence Visa'] },
  { slug: 'venezuela', name: 'Venezuela', demonym: 'Venezuelan', region: 'americas', insuranceRequired: false, publicSystemName: 'State Healthcare', currency: 'VES', insuranceCostRange: '$80-180/month', publicCostRange: 'Minimal', visaTypes: ['Work Visa', 'Business Visa'], notes: 'Limited expat services' },
  { slug: 'guyana', name: 'Guyana', demonym: 'Guyanese', region: 'americas', insuranceRequired: false, publicSystemName: 'GPH', currency: 'GYD', insuranceCostRange: '$60-150/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'suriname', name: 'Suriname', demonym: 'Surinamese', region: 'americas', insuranceRequired: false, publicSystemName: 'SZF', currency: 'SRD', insuranceCostRange: '$60-150/month', publicCostRange: '$15-30/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'belize', name: 'Belize', demonym: 'Belizean', region: 'americas', insuranceRequired: false, publicSystemName: 'MOH', currency: 'BZD', insuranceCostRange: '$80-180/month', publicCostRange: '$10-25/month', visaTypes: ['QRP', 'Work Permit', 'Permanent Residence'] },
  { slug: 'guatemala', name: 'Guatemala', demonym: 'Guatemalan', region: 'americas', insuranceRequired: false, publicSystemName: 'IGSS', currency: 'GTQ', insuranceCostRange: '$70-160/month', publicCostRange: '$15-30/month', visaTypes: ['Temporary Residence', 'Pensionado'] },
  { slug: 'honduras', name: 'Honduras', demonym: 'Honduran', region: 'americas', insuranceRequired: false, publicSystemName: 'IHSS', currency: 'HNL', insuranceCostRange: '$60-140/month', publicCostRange: '$10-25/month', visaTypes: ['Residence Permit', 'Rentista Visa'] },
  { slug: 'el-salvador', name: 'El Salvador', demonym: 'Salvadoran', region: 'americas', insuranceRequired: false, publicSystemName: 'ISSS', currency: 'USD', insuranceCostRange: '$70-160/month', publicCostRange: '$15-30/month', visaTypes: ['Temporary Residence', 'Rentista Visa'] },
  { slug: 'nicaragua', name: 'Nicaragua', demonym: 'Nicaraguan', region: 'americas', insuranceRequired: false, publicSystemName: 'MINSA', currency: 'NIO', insuranceCostRange: '$50-120/month', publicCostRange: '$10-20/month', visaTypes: ['Residence Permit', 'Retirement Visa'] },
  { slug: 'dominican-republic', name: 'Dominican Republic', demonym: 'Dominican', region: 'americas', insuranceRequired: false, publicSystemName: 'SeNaSa', currency: 'DOP', insuranceCostRange: '$80-180/month', publicCostRange: '$15-35/month', visaTypes: ['Residence Visa', 'Retirement Visa', 'Investor Visa'] },
  { slug: 'jamaica', name: 'Jamaica', demonym: 'Jamaican', region: 'americas', insuranceRequired: false, publicSystemName: 'NHF', currency: 'JMD', insuranceCostRange: '$100-220/month', publicCostRange: '$15-35/month', visaTypes: ['Work Permit', 'Retirement Visa'] },
  { slug: 'bahamas', name: 'Bahamas', demonym: 'Bahamian', region: 'americas', insuranceRequired: false, publicSystemName: 'PHA', currency: 'BSD', insuranceCostRange: '$150-350/month', publicCostRange: '$25-50/visit', visaTypes: ['BEATS Program', 'Annual Residence Permit'] },
  { slug: 'barbados', name: 'Barbados', demonym: 'Barbadian', region: 'americas', insuranceRequired: false, publicSystemName: 'QEH', currency: 'BBD', insuranceCostRange: '$120-280/month', publicCostRange: '$20-40/visit', visaTypes: ['Welcome Stamp', 'Work Permit'] },
  { slug: 'trinidad-tobago', name: 'Trinidad and Tobago', demonym: 'Trinidadian', region: 'americas', insuranceRequired: false, publicSystemName: 'RHA', currency: 'TTD', insuranceCostRange: '$100-220/month', publicCostRange: '$15-30/visit', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'cuba', name: 'Cuba', demonym: 'Cuban', region: 'americas', insuranceRequired: true, publicSystemName: 'SNS', currency: 'CUP', insuranceCostRange: '$80-180/month', publicCostRange: 'Mandatory travel insurance', visaTypes: ['Business Visa', 'D-1 Visa'], notes: 'Mandatory travel insurance' },
  { slug: 'haiti', name: 'Haiti', demonym: 'Haitian', region: 'americas', insuranceRequired: false, publicSystemName: 'MSPP', currency: 'HTG', insuranceCostRange: '$60-150/month', publicCostRange: '$5-15/month', visaTypes: ['Work Visa', 'Residence Permit'], notes: 'Limited healthcare infrastructure' },
  { slug: 'puerto-rico', name: 'Puerto Rico', demonym: 'Puerto Rican', region: 'americas', insuranceRequired: false, publicSystemName: 'Medicare/Medicaid', currency: 'USD', insuranceCostRange: '$200-450/month', publicCostRange: 'US rates', visaTypes: ['US Territory - no visa needed for US citizens'] },
  { slug: 'aruba', name: 'Aruba', demonym: 'Aruban', region: 'americas', insuranceRequired: false, publicSystemName: 'AZV', currency: 'AWG', insuranceCostRange: '$150-350/month', publicCostRange: '$50-100/month', visaTypes: ['One Happy Workation', 'Residence Permit'] },
  { slug: 'curacao', name: 'Curaçao', demonym: 'Curaçaoan', region: 'americas', insuranceRequired: false, publicSystemName: 'SVB', currency: 'ANG', insuranceCostRange: '$120-280/month', publicCostRange: '$40-80/month', visaTypes: ['Digital Nomad Visa', 'Residence Permit'] },
  { slug: 'cayman-islands', name: 'Cayman Islands', demonym: 'Caymanian', region: 'americas', insuranceRequired: true, publicSystemName: 'HSA', currency: 'KYD', insuranceCostRange: '$250-550/month', publicCostRange: 'Mandatory insurance', visaTypes: ['Work Permit', 'Global Citizen Concierge'] },
  { slug: 'bermuda', name: 'Bermuda', demonym: 'Bermudian', region: 'americas', insuranceRequired: true, publicSystemName: 'HIP/FutureCare', currency: 'BMD', insuranceCostRange: '$300-600/month', publicCostRange: 'Mandatory insurance', visaTypes: ['Work Permit', 'Digital Nomad Visa'] },
  { slug: 'virgin-islands', name: 'US Virgin Islands', demonym: 'Virgin Islander', region: 'americas', insuranceRequired: false, publicSystemName: 'US Healthcare', currency: 'USD', insuranceCostRange: '$200-450/month', publicCostRange: 'US rates', visaTypes: ['US Territory - no visa needed'] },
  { slug: 'st-kitts-nevis', name: 'St Kitts and Nevis', demonym: 'Kittitian', region: 'americas', insuranceRequired: false, publicSystemName: 'JNF Hospital', currency: 'XCD', insuranceCostRange: '$120-280/month', publicCostRange: '$20-40/visit', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'antigua-barbuda', name: 'Antigua and Barbuda', demonym: 'Antiguan', region: 'americas', insuranceRequired: false, publicSystemName: 'MBS', currency: 'XCD', insuranceCostRange: '$120-280/month', publicCostRange: '$15-35/visit', visaTypes: ['Nomad Digital Residence', 'Work Permit'] },
  { slug: 'grenada', name: 'Grenada', demonym: 'Grenadian', region: 'americas', insuranceRequired: false, publicSystemName: 'MOHSD', currency: 'XCD', insuranceCostRange: '$100-220/month', publicCostRange: '$15-30/visit', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'st-lucia', name: 'Saint Lucia', demonym: 'Saint Lucian', region: 'americas', insuranceRequired: false, publicSystemName: 'MOH', currency: 'XCD', insuranceCostRange: '$100-220/month', publicCostRange: '$15-30/visit', visaTypes: ['Live It', 'Work Permit'] },
  { slug: 'dominica', name: 'Dominica', demonym: 'Dominican', region: 'americas', insuranceRequired: false, publicSystemName: 'PMH', currency: 'XCD', insuranceCostRange: '$80-180/month', publicCostRange: '$10-25/visit', visaTypes: ['Extended Stay Visa', 'Work Permit'] },
  { slug: 'st-vincent', name: 'St Vincent and the Grenadines', demonym: 'Vincentian', region: 'americas', insuranceRequired: false, publicSystemName: 'MOH', currency: 'XCD', insuranceCostRange: '$80-180/month', publicCostRange: '$10-25/visit', visaTypes: ['Work Permit', 'Residence Permit'] },

  // =====================
  // MIDDLE EAST
  // =====================
  { slug: 'israel', name: 'Israel', demonym: 'Israeli', region: 'middle-east', insuranceRequired: true, publicSystemName: 'Kupat Holim', currency: 'ILS', insuranceCostRange: '$200-450/month', publicCostRange: '$100-200/month', visaTypes: ['A/1 Work Visa', 'B/1 Work Visa'] },
  { slug: 'jordan', name: 'Jordan', demonym: 'Jordanian', region: 'middle-east', insuranceRequired: false, publicSystemName: 'MOH', currency: 'JOD', insuranceCostRange: '$80-180/month', publicCostRange: '$20-40/month', visaTypes: ['Work Permit', 'Investor Visa'] },
  { slug: 'lebanon', name: 'Lebanon', demonym: 'Lebanese', region: 'middle-east', insuranceRequired: false, publicSystemName: 'NSSF', currency: 'LBP', insuranceCostRange: '$100-220/month', publicCostRange: '$20-50/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'saudi-arabia', name: 'Saudi Arabia', demonym: 'Saudi', region: 'middle-east', insuranceRequired: true, publicSystemName: 'MOH', currency: 'SAR', insuranceCostRange: '$150-350/month', publicCostRange: 'Employer-provided', visaTypes: ['Work Visa', 'Premium Residency'] },
  { slug: 'qatar', name: 'Qatar', demonym: 'Qatari', region: 'middle-east', insuranceRequired: true, publicSystemName: 'HMC', currency: 'QAR', insuranceCostRange: '$150-350/month', publicCostRange: '$30-60/visit', visaTypes: ['Work Visa', 'Family Residence Permit'] },
  { slug: 'kuwait', name: 'Kuwait', demonym: 'Kuwaiti', region: 'middle-east', insuranceRequired: true, publicSystemName: 'MOH', currency: 'KWD', insuranceCostRange: '$100-250/month', publicCostRange: '$15-30/year', visaTypes: ['Work Visa', 'Residence Visa'] },
  { slug: 'bahrain', name: 'Bahrain', demonym: 'Bahraini', region: 'middle-east', insuranceRequired: true, publicSystemName: 'NHRA', currency: 'BHD', insuranceCostRange: '$100-250/month', publicCostRange: '$20-40/month', visaTypes: ['Work Visa', 'Golden Visa', 'Digital Nomad Visa'] },
  { slug: 'oman', name: 'Oman', demonym: 'Omani', region: 'middle-east', insuranceRequired: true, publicSystemName: 'MOH', currency: 'OMR', insuranceCostRange: '$100-250/month', publicCostRange: '$15-35/visit', visaTypes: ['Work Visa', 'Investor Residence', 'Retirement Visa'] },
  { slug: 'iraq', name: 'Iraq', demonym: 'Iraqi', region: 'middle-east', insuranceRequired: false, publicSystemName: 'MOH', currency: 'IQD', insuranceCostRange: '$80-180/month', publicCostRange: '$10-25/month', visaTypes: ['Work Visa', 'Business Visa'], notes: 'Limited expat infrastructure' },
  { slug: 'iran', name: 'Iran', demonym: 'Iranian', region: 'middle-east', insuranceRequired: true, publicSystemName: 'MOH', currency: 'IRR', insuranceCostRange: '$60-150/month', publicCostRange: '$10-25/month', visaTypes: ['Work Visa', 'Business Visa'], notes: 'Sanctions may limit options' },
  { slug: 'yemen', name: 'Yemen', demonym: 'Yemeni', region: 'middle-east', insuranceRequired: false, publicSystemName: 'MOH', currency: 'YER', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Visa'], notes: 'Check current situation' },
  { slug: 'syria', name: 'Syria', demonym: 'Syrian', region: 'middle-east', insuranceRequired: false, publicSystemName: 'MOH', currency: 'SYP', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Visa required'], notes: 'Check current situation' },

  // =====================
  // AFRICA
  // =====================
  { slug: 'south-africa', name: 'South Africa', demonym: 'South African', region: 'africa', insuranceRequired: false, publicSystemName: 'Department of Health', currency: 'ZAR', insuranceCostRange: '$100-250/month', publicCostRange: '$20-50/month', visaTypes: ['Critical Skills Visa', 'Retirement Visa', 'Business Visa'] },
  { slug: 'morocco', name: 'Morocco', demonym: 'Moroccan', region: 'africa', insuranceRequired: false, publicSystemName: 'AMO/RAMED', currency: 'MAD', insuranceCostRange: '$60-150/month', publicCostRange: '$15-35/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'egypt', name: 'Egypt', demonym: 'Egyptian', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'EGP', insuranceCostRange: '$50-120/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Residence Visa'] },
  { slug: 'tunisia', name: 'Tunisia', demonym: 'Tunisian', region: 'africa', insuranceRequired: false, publicSystemName: 'CNAM', currency: 'TND', insuranceCostRange: '$50-120/month', publicCostRange: '$15-30/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'kenya', name: 'Kenya', demonym: 'Kenyan', region: 'africa', insuranceRequired: false, publicSystemName: 'NHIF', currency: 'KES', insuranceCostRange: '$80-180/month', publicCostRange: '$15-35/month', visaTypes: ['Work Permit', 'Digital Nomad Permit'] },
  { slug: 'tanzania', name: 'Tanzania', demonym: 'Tanzanian', region: 'africa', insuranceRequired: false, publicSystemName: 'NHIF', currency: 'TZS', insuranceCostRange: '$70-160/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'uganda', name: 'Uganda', demonym: 'Ugandan', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'UGX', insuranceCostRange: '$60-140/month', publicCostRange: '$10-20/month', visaTypes: ['Work Permit', 'Special Pass'] },
  { slug: 'rwanda', name: 'Rwanda', demonym: 'Rwandan', region: 'africa', insuranceRequired: true, publicSystemName: 'CBHI/RSSB', currency: 'RWF', insuranceCostRange: '$60-140/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Investor Visa'] },
  { slug: 'ethiopia', name: 'Ethiopia', demonym: 'Ethiopian', region: 'africa', insuranceRequired: false, publicSystemName: 'CBHI', currency: 'ETB', insuranceCostRange: '$50-120/month', publicCostRange: '$10-20/month', visaTypes: ['Work Permit', 'Origin ID Card'] },
  { slug: 'ghana', name: 'Ghana', demonym: 'Ghanaian', region: 'africa', insuranceRequired: false, publicSystemName: 'NHIS', currency: 'GHS', insuranceCostRange: '$70-160/month', publicCostRange: '$15-30/month', visaTypes: ['Work Permit', 'Right to Abode'] },
  { slug: 'nigeria', name: 'Nigeria', demonym: 'Nigerian', region: 'africa', insuranceRequired: false, publicSystemName: 'NHIS', currency: 'NGN', insuranceCostRange: '$80-180/month', publicCostRange: '$15-35/month', visaTypes: ['Work Permit', 'Subject to Regularization'] },
  { slug: 'senegal', name: 'Senegal', demonym: 'Senegalese', region: 'africa', insuranceRequired: false, publicSystemName: 'CMU', currency: 'XOF', insuranceCostRange: '$60-140/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Carte de Séjour'] },
  { slug: 'ivory-coast', name: 'Ivory Coast', demonym: 'Ivorian', region: 'africa', insuranceRequired: false, publicSystemName: 'CMU', currency: 'XOF', insuranceCostRange: '$60-140/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Carte de Séjour'] },
  { slug: 'cameroon', name: 'Cameroon', demonym: 'Cameroonian', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'XAF', insuranceCostRange: '$50-120/month', publicCostRange: '$10-20/month', visaTypes: ['Work Permit', 'Carte de Séjour'] },
  { slug: 'namibia', name: 'Namibia', demonym: 'Namibian', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'NAD', insuranceCostRange: '$80-180/month', publicCostRange: '$15-30/month', visaTypes: ['Work Permit', 'Permanent Residence'] },
  { slug: 'botswana', name: 'Botswana', demonym: 'Motswana', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'BWP', insuranceCostRange: '$80-180/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'zambia', name: 'Zambia', demonym: 'Zambian', region: 'africa', insuranceRequired: false, publicSystemName: 'NHIMA', currency: 'ZMW', insuranceCostRange: '$60-140/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Employment Permit'] },
  { slug: 'zimbabwe', name: 'Zimbabwe', demonym: 'Zimbabwean', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'ZWL', insuranceCostRange: '$70-160/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'mozambique', name: 'Mozambique', demonym: 'Mozambican', region: 'africa', insuranceRequired: false, publicSystemName: 'SNS', currency: 'MZN', insuranceCostRange: '$60-140/month', publicCostRange: '$10-20/month', visaTypes: ['Work Visa', 'DIRE'] },
  { slug: 'mauritius', name: 'Mauritius', demonym: 'Mauritian', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'MUR', insuranceCostRange: '$80-180/month', publicCostRange: '$15-30/month', visaTypes: ['Occupation Permit', 'Premium Visa'] },
  { slug: 'seychelles', name: 'Seychelles', demonym: 'Seychellois', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'SCR', insuranceCostRange: '$100-220/month', publicCostRange: '$20-40/month', visaTypes: ['Gainful Occupation Permit', 'Workcation Retreat'] },
  { slug: 'madagascar', name: 'Madagascar', demonym: 'Malagasy', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'MGA', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Visa', 'Long Stay Visa'] },
  { slug: 'reunion', name: 'Réunion', demonym: 'Réunionese', region: 'africa', insuranceRequired: true, publicSystemName: 'French Healthcare', currency: 'EUR', insuranceCostRange: '€120-280/month', publicCostRange: '€50-100/month', visaTypes: ['French territory - EU rules'] },
  { slug: 'cape-verde', name: 'Cape Verde', demonym: 'Cape Verdean', region: 'africa', insuranceRequired: false, publicSystemName: 'INPS', currency: 'CVE', insuranceCostRange: '$60-140/month', publicCostRange: '$10-25/month', visaTypes: ['Remote Working Visa', 'Residence Permit'] },
  { slug: 'angola', name: 'Angola', demonym: 'Angolan', region: 'africa', insuranceRequired: false, publicSystemName: 'SNS', currency: 'AOA', insuranceCostRange: '$100-220/month', publicCostRange: '$15-35/month', visaTypes: ['Work Visa', 'Temporary Residence'] },
  { slug: 'drc', name: 'Democratic Republic of Congo', demonym: 'Congolese', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'CDF', insuranceCostRange: '$80-180/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Établissement Visa'] },
  { slug: 'congo', name: 'Republic of Congo', demonym: 'Congolese', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'XAF', insuranceCostRange: '$70-160/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Carte de Séjour'] },
  { slug: 'gabon', name: 'Gabon', demonym: 'Gabonese', region: 'africa', insuranceRequired: false, publicSystemName: 'CNAMGS', currency: 'XAF', insuranceCostRange: '$80-180/month', publicCostRange: '$20-40/month', visaTypes: ['Work Permit', 'Carte de Séjour'] },
  { slug: 'mali', name: 'Mali', demonym: 'Malian', region: 'africa', insuranceRequired: false, publicSystemName: 'AMO', currency: 'XOF', insuranceCostRange: '$50-120/month', publicCostRange: '$10-20/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'burkina-faso', name: 'Burkina Faso', demonym: 'Burkinabè', region: 'africa', insuranceRequired: false, publicSystemName: 'AMU', currency: 'XOF', insuranceCostRange: '$50-120/month', publicCostRange: '$10-20/month', visaTypes: ['Work Permit', 'Carte de Séjour'] },
  { slug: 'niger', name: 'Niger', demonym: 'Nigerien', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'XOF', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'benin', name: 'Benin', demonym: 'Beninese', region: 'africa', insuranceRequired: false, publicSystemName: 'ARCH', currency: 'XOF', insuranceCostRange: '$50-120/month', publicCostRange: '$10-20/month', visaTypes: ['Work Permit', 'Digital Nomad Visa'] },
  { slug: 'togo', name: 'Togo', demonym: 'Togolese', region: 'africa', insuranceRequired: false, publicSystemName: 'AMU', currency: 'XOF', insuranceCostRange: '$50-120/month', publicCostRange: '$10-20/month', visaTypes: ['Work Permit', 'Carte de Séjour'] },
  { slug: 'guinea', name: 'Guinea', demonym: 'Guinean', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'GNF', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'sierra-leone', name: 'Sierra Leone', demonym: 'Sierra Leonean', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'SLE', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'liberia', name: 'Liberia', demonym: 'Liberian', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'LRD', insuranceCostRange: '$60-140/month', publicCostRange: '$10-20/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'gambia', name: 'The Gambia', demonym: 'Gambian', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'GMD', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'mauritania', name: 'Mauritania', demonym: 'Mauritanian', region: 'africa', insuranceRequired: false, publicSystemName: 'CNAM', currency: 'MRU', insuranceCostRange: '$50-120/month', publicCostRange: '$10-20/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'algeria', name: 'Algeria', demonym: 'Algerian', region: 'africa', insuranceRequired: false, publicSystemName: 'CNAS', currency: 'DZD', insuranceCostRange: '$50-120/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'libya', name: 'Libya', demonym: 'Libyan', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'LYD', insuranceCostRange: '$60-140/month', publicCostRange: '$10-20/month', visaTypes: ['Work Visa'], notes: 'Check current situation' },
  { slug: 'sudan', name: 'Sudan', demonym: 'Sudanese', region: 'africa', insuranceRequired: false, publicSystemName: 'NHIF', currency: 'SDG', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit'], notes: 'Check current situation' },
  { slug: 'south-sudan', name: 'South Sudan', demonym: 'South Sudanese', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'SSP', insuranceCostRange: '$60-140/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit'], notes: 'Limited infrastructure' },
  { slug: 'eritrea', name: 'Eritrea', demonym: 'Eritrean', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'ERN', insuranceCostRange: '$50-120/month', publicCostRange: '$5-10/month', visaTypes: ['Work Permit'], notes: 'Very limited access' },
  { slug: 'djibouti', name: 'Djibouti', demonym: 'Djiboutian', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'DJF', insuranceCostRange: '$80-180/month', publicCostRange: '$15-30/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'somalia', name: 'Somalia', demonym: 'Somali', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'SOS', insuranceCostRange: '$60-140/month', publicCostRange: '$5-15/month', visaTypes: ['Visa on Arrival'], notes: 'Check security situation' },
  { slug: 'comoros', name: 'Comoros', demonym: 'Comorian', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'KMF', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Economic Citizenship', 'Work Permit'] },
  { slug: 'mayotte', name: 'Mayotte', demonym: 'Mahorais', region: 'africa', insuranceRequired: true, publicSystemName: 'French Healthcare', currency: 'EUR', insuranceCostRange: '€120-280/month', publicCostRange: '€50-100/month', visaTypes: ['French territory - EU rules'] },
  { slug: 'sao-tome', name: 'São Tomé and Príncipe', demonym: 'São Toméan', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'STN', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'equatorial-guinea', name: 'Equatorial Guinea', demonym: 'Equatoguinean', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'XAF', insuranceCostRange: '$80-180/month', publicCostRange: '$15-30/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'central-african-republic', name: 'Central African Republic', demonym: 'Central African', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'XAF', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit'], notes: 'Check security situation' },
  { slug: 'chad', name: 'Chad', demonym: 'Chadian', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'XAF', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'burundi', name: 'Burundi', demonym: 'Burundian', region: 'africa', insuranceRequired: false, publicSystemName: 'CAM', currency: 'BIF', insuranceCostRange: '$50-120/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'malawi', name: 'Malawi', demonym: 'Malawian', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'MWK', insuranceCostRange: '$60-140/month', publicCostRange: '$5-15/month', visaTypes: ['Work Permit', 'TEP'] },
  { slug: 'lesotho', name: 'Lesotho', demonym: 'Mosotho', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'LSL', insuranceCostRange: '$60-140/month', publicCostRange: '$10-20/month', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'eswatini', name: 'Eswatini', demonym: 'Swazi', region: 'africa', insuranceRequired: false, publicSystemName: 'MOH', currency: 'SZL', insuranceCostRange: '$70-160/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Residence Permit'] },

  // =====================
  // OCEANIA
  // =====================
  { slug: 'new-zealand', name: 'New Zealand', demonym: 'New Zealander', region: 'oceania', insuranceRequired: false, publicSystemName: 'ACC/Public Health', currency: 'NZD', insuranceCostRange: '$150-350/month', publicCostRange: 'Subsidized for residents', visaTypes: ['Skilled Migrant', 'Work to Residence', 'Investor'] },
  { slug: 'fiji', name: 'Fiji', demonym: 'Fijian', region: 'oceania', insuranceRequired: false, publicSystemName: 'MOH', currency: 'FJD', insuranceCostRange: '$80-180/month', publicCostRange: '$10-25/visit', visaTypes: ['Work Permit', 'Investor Permit'] },
  { slug: 'papua-new-guinea', name: 'Papua New Guinea', demonym: 'Papua New Guinean', region: 'oceania', insuranceRequired: false, publicSystemName: 'MOH', currency: 'PGK', insuranceCostRange: '$100-220/month', publicCostRange: '$10-25/month', visaTypes: ['Work Permit', 'Business Visa'] },
  { slug: 'samoa', name: 'Samoa', demonym: 'Samoan', region: 'oceania', insuranceRequired: false, publicSystemName: 'NHS', currency: 'WST', insuranceCostRange: '$70-160/month', publicCostRange: '$10-20/visit', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'tonga', name: 'Tonga', demonym: 'Tongan', region: 'oceania', insuranceRequired: false, publicSystemName: 'MOH', currency: 'TOP', insuranceCostRange: '$70-160/month', publicCostRange: '$10-20/visit', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'vanuatu', name: 'Vanuatu', demonym: 'Ni-Vanuatu', region: 'oceania', insuranceRequired: false, publicSystemName: 'MOH', currency: 'VUV', insuranceCostRange: '$80-180/month', publicCostRange: '$15-30/visit', visaTypes: ['Work Permit', 'Investor Permit'] },
  { slug: 'solomon-islands', name: 'Solomon Islands', demonym: 'Solomon Islander', region: 'oceania', insuranceRequired: false, publicSystemName: 'MOH', currency: 'SBD', insuranceCostRange: '$70-160/month', publicCostRange: '$10-20/visit', visaTypes: ['Work Permit', 'Business Visa'] },
  { slug: 'new-caledonia', name: 'New Caledonia', demonym: 'New Caledonian', region: 'oceania', insuranceRequired: true, publicSystemName: 'CAFAT', currency: 'XPF', insuranceCostRange: '€150-350/month', publicCostRange: '€50-100/month', visaTypes: ['French territory - EU rules'] },
  { slug: 'french-polynesia', name: 'French Polynesia', demonym: 'French Polynesian', region: 'oceania', insuranceRequired: true, publicSystemName: 'CPS', currency: 'XPF', insuranceCostRange: '€150-350/month', publicCostRange: '€50-100/month', visaTypes: ['French territory - EU rules'] },
  { slug: 'guam', name: 'Guam', demonym: 'Guamanian', region: 'oceania', insuranceRequired: false, publicSystemName: 'US Healthcare', currency: 'USD', insuranceCostRange: '$200-450/month', publicCostRange: 'US rates', visaTypes: ['US territory - US visa rules'] },
  { slug: 'palau', name: 'Palau', demonym: 'Palauan', region: 'oceania', insuranceRequired: false, publicSystemName: 'MOH', currency: 'USD', insuranceCostRange: '$80-180/month', publicCostRange: '$15-30/visit', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'micronesia', name: 'Micronesia', demonym: 'Micronesian', region: 'oceania', insuranceRequired: false, publicSystemName: 'MOH', currency: 'USD', insuranceCostRange: '$70-160/month', publicCostRange: '$10-25/visit', visaTypes: ['Work Permit', 'Entry Permit'] },
  { slug: 'marshall-islands', name: 'Marshall Islands', demonym: 'Marshallese', region: 'oceania', insuranceRequired: false, publicSystemName: 'MOH', currency: 'USD', insuranceCostRange: '$70-160/month', publicCostRange: '$10-25/visit', visaTypes: ['Work Permit', 'Residence Permit'] },
  { slug: 'kiribati', name: 'Kiribati', demonym: 'I-Kiribati', region: 'oceania', insuranceRequired: false, publicSystemName: 'MOH', currency: 'AUD', insuranceCostRange: '$60-140/month', publicCostRange: '$5-15/visit', visaTypes: ['Work Permit', 'Special Permit'] },
  { slug: 'nauru', name: 'Nauru', demonym: 'Nauruan', region: 'oceania', insuranceRequired: false, publicSystemName: 'RON Hospital', currency: 'AUD', insuranceCostRange: '$80-180/month', publicCostRange: '$10-25/visit', visaTypes: ['Work Permit', 'Business Visa'] },
  { slug: 'tuvalu', name: 'Tuvalu', demonym: 'Tuvaluan', region: 'oceania', insuranceRequired: false, publicSystemName: 'PMH', currency: 'AUD', insuranceCostRange: '$60-140/month', publicCostRange: '$5-15/visit', visaTypes: ['Work Permit', 'Special Permit'] },
  { slug: 'cook-islands', name: 'Cook Islands', demonym: 'Cook Islander', region: 'oceania', insuranceRequired: false, publicSystemName: 'MOH', currency: 'NZD', insuranceCostRange: '$80-180/month', publicCostRange: '$15-30/visit', visaTypes: ['Work Permit'] },
  { slug: 'niue', name: 'Niue', demonym: 'Niuean', region: 'oceania', insuranceRequired: false, publicSystemName: 'Niue Foou Hospital', currency: 'NZD', insuranceCostRange: '$70-160/month', publicCostRange: '$10-25/visit', visaTypes: ['Work Permit'] },
  { slug: 'tokelau', name: 'Tokelau', demonym: 'Tokelauan', region: 'oceania', insuranceRequired: false, publicSystemName: 'NZ Healthcare', currency: 'NZD', insuranceCostRange: '$70-160/month', publicCostRange: 'NZ rules', visaTypes: ['Special permit required'] },
];

// Remove existing countries
export const newCountries = countryMetadata.filter(c => !existingSlugs.has(c.slug));

console.log(`Total countries in metadata: ${countryMetadata.length}`);
console.log(`Existing handcrafted pages: ${existingSlugs.size}`);
console.log(`New countries to generate: ${newCountries.length}`);
